In [3]:
import pandas as pd 
import pickle

dbfile = open("DataBase/1h/BTCUSDT.p",'rb')
df = pickle.load(dbfile)
dbfile.close()

In [4]:
df

                         open      high       low     close        volume
timestamp
2017-08-17 04:00:00   4261.48   4313.62   4261.32   4308.83     47.181009
2017-08-17 05:00:00   4308.83   4328.69   4291.37   4315.32     23.234916
2017-08-17 06:00:00   4330.29   4345.45   4309.37   4324.35      7.229691
2017-08-17 07:00:00   4316.62   4349.99   4287.41   4349.99      4.443249
2017-08-17 08:00:00   4333.32   4377.85   4333.32   4360.69      0.972807
...                       ...       ...       ...       ...           ...
2022-10-24 18:00:00  19284.65  19349.55  19281.85  19334.65   7710.412580
2022-10-24 19:00:00  19334.65  19425.05  19330.00  19343.23  10079.966380
2022-10-24 20:00:00  19343.95  19381.47  19301.11  19378.53   6218.250490
2022-10-24 21:00:00  19378.53  19419.15  19329.66  19366.42   5921.400960
2022-10-24 22:00:00  19366.42  19373.95  19303.20  19324.62   2169.757000

[1999 rows x 5 columns]